### ISSUE TITLE
How to resolve?

### ISSUE THREAD

**Issue by flightmonkey15** [llSourcell/deep_dream_challenge#4]
Traceback (most recent call last):
  File "C:/Users//Desktop/deep_dream.py", line 186, in <module>
    main()
  File "C:/Users//Desktop/deep_dream.py", line 35, in main
    graph_def.ParseFromString(f.read())
  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 112, in read
    return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: reached end of file

**Comment by piteight** [comment]
Maybe path of the inception model graph is in different place. 

`    data_dir = './where/is/my/script/graph/etc/'

    img_noise = np.random.uniform(size=(224, 224, 3)) + 100.0

    model_fn = '/inside/my/data_dir/tensorflow_inception_graph.pb'

    # Step 2 - Creating Tensorflow session and loading the model
    graph = tf.Graph()
    sess = tf.InteractiveSession(graph=graph)
    with tf.gfile.FastGFile(os.path.join(data_dir, model_fn), 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())`

Working on Ubuntu, 
I don't use conda environment
